export enum StitchTypes {
  Single = "sc",
  Double = "dc",
  Slip = "slst",
  HalfDouble = "hdc",
  Triple = "tr",
  Increase = "inc",
  Decrease = "dec",
  BackLoopOnly = "blo",
  FrontLoopOnly = "flo",
  Chain = "ch",
  FrontPost = "fp",
  BackPost = "bp",
  YarnOver = "yo",
  Popcorn = "pop",
  Repeat = "rep",
  Round = "rnd",
}
